---

- name: push config to git
  hosts: cisco
  connection: network_cli
  gather_facts: no
  tasks:

  - name: make sure git is up to date
    git:
      repo: https://github.com/pharriso/tower_workshop.git
      dest: /tmp/tower_workshop
      clone: yes
      update: yes
    delegate_to: localhost

  - name: backup the config
    ios_config:
      backup: yes
    register: config_output

  - name: rename backup
    copy:
      src: "{{config_output.backup_path}}"
      dest: "/tmp/tower_workshop/configs/{{inventory_hostname}}.config"
    delegate_to: localhost

  - name: remove non config lines
    lineinfile:
      path: "/tmp/tower_workshop/configs/{{inventory_hostname}}.config"
      line: "Building configuration..."
      state: absent
    delegate_to: localhost

  - name: remove non config lines - regexp
    lineinfile:
      path: "/tmp/tower_workshop/configs/{{inventory_hostname}}.config"
      regexp: 'Current configuration.*'
      state: absent
    delegate_to: localhost

  - name: add configs
    shell: "git add *"
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost

  - name: git commit
    shell: git commit -m "Ansible Backup" 
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost

  - name: push to git
    shell: git push 
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost
