---

- name: push config to git
  hosts: cisco
  connection: network_cli
  gather_facts: no
  tasks:

  - name: clear out directory first
    file:
      path: /tmp/tower_workshop
      state: absent
    delegate_to: localhost

  - name: make sure git is up to date
    git:
      repo: git@github.com:pharriso/tower_workshop.git
      dest: /tmp/tower_workshop
      clone: yes
      update: yes
    delegate_to: localhost

  - name: backup the config
    ios_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}.cfg"
        dir_path: /tmp/tower_workshop/configs

  - name: remove non config lines
    lineinfile:
      path: "/tmp/tower_workshop/configs/{{inventory_hostname}}.cfg"
      line: "Building configuration..."
      state: absent
    delegate_to: localhost

  - name: remove non config lines - regexp
    lineinfile:
      path: "/tmp/tower_workshop/configs/{{inventory_hostname}}.cfg"
      regexp: 'Current configuration.*'
      state: absent
    delegate_to: localhost

  - name: remove timestamp
    lineinfile:
      path: "/tmp/tower_workshop/configs/{{inventory_hostname}}.cfg"
      regexp: 'Last configuration change.*'
      state: absent

  - name: add configs
    shell: "git add *"
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost

  - name: git config
    shell: git config --global user.name "ansible backup" && git config --global user.email "backup@tower"
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost

  - name: git commit 
    shell: git commit -m "Ansible backup"
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost

  - name: push to git
    shell: git push 
    args:
      chdir: /tmp/tower_workshop
    delegate_to: localhost
    register: git_push
    failed_when: 
      - '"nothing to commit" not in git_push.stdout'
      - git_push.rc == 1
