---
- name: RESTORE CONFIGURATION
  hosts: cisco
  gather_facts: no

  tasks:
    - name: COPY RUNNING CONFIG TO ROUTER
      command: scp ./backup/{{inventory_hostname}}.config  {{inventory_hostname}}:/{{inventory_hostname}}.config
      delegate_to: localhost

- name: RESTORE CONFIGURATION
  hosts: cisco
  connection: network_cli
  gather_facts: no
  tasks:

    - name: CONFIG REPLACE
      ios_command:
        commands:
          - config replace flash:{{inventory_hostname}}.config force
      tags: restore
