---
- name: SNMP RO/RW STRING CONFIGURATION
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:

    - name: ENSURE THAT THE DESIRED SNMP STRINGS ARE PRESENT
      ios_config:
        commands:
          - snmp-server community ansible-public RO
          - snmp-server community ansible-private RW
          - snmp-server community ansible-test RO
      register: config

    - name: log incident in servicenow
      snow_record:
        username: "{{ snow_user }}"
        password: "{{ snow_password }}"
        instance: "{{ snow_instance }}"
        state: present
        table: incident
        data:
          short_description: "Configuration drift for {{ inventory_hostname }}"
          comments: "Ticket raised by Ansible Automation. Check job id {{ tower_job_id }} in Ansible Tower for further details."
          severity: 3
          priority: 2
      register: snow_var
      delegate_to: localhost
      when: config is changed
      become: false

    - name: display servicenow incident number
      debug:
        msg: "ServiceNow incident number is {{ snow_var.record.number }}."
      delegate_to: localhost
      when: config is changed
      become: false
